master:
  image: jenkins:latest
  volumes:
    - ./docker-home:/var/jenkins_home
  links:
    - slave
  environment:
    - SERVICE_NAME=jenkins

slave:
  image: tehranian/dind-jenkins-slave:latest
  privileged: true
